# Generated by Django 2.1.4 on 2018-12-30 03:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Imagem')),
                ('background_color', models.CharField(choices=[('0097dc', 'Light Blue'), ('0186c4', 'Dark Blue')], default='', max_length=6, verbose_name='Cor de Fundo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Bloco de Conteúdo',
                'verbose_name_plural': 'Blocos de Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=150, verbose_name='Dono do Website')),
                ('occupation', models.CharField(default='', max_length=150, verbose_name='Ocupação')),
                ('additional_info', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Informações Adicionais')),
            ],
            options={
                'verbose_name': 'Informação Principal',
                'verbose_name_plural': 'Informações Principais',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-Mail')),
                ('linkedin', models.URLField(default='', verbose_name='LinkedIn')),
                ('github', models.URLField(default='', verbose_name='GitHub')),
                ('facebook', models.URLField(blank=True, default='', null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='', null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, default='', null=True, verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
    ]
