# Generated by Django 2.1.4 on 2018-12-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181230_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img', verbose_name='Imagem'),
        ),
    ]
