# Generated by Django 2.1.4 on 2018-12-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181230_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150, verbose_name='Texto')),
                ('type', models.CharField(choices=[('btn', 'Basic'), ('btn btn-primary', 'Primary'), ('btn btn-secondary', 'Secondary'), ('btn btn-success', 'Success'), ('btn btn-info', 'Info'), ('btn btn-warning', 'Warning'), ('btn btn-danger', 'Danger'), ('btn btn-dark', 'Dark'), ('btn btn-light', 'Light'), ('btn btn-link', 'Link')], default='', max_length=32, verbose_name='Tipo')),
                ('link', models.URLField(default='', verbose_name='Link')),
                ('size', models.CharField(choices=[('btn-lg', 'Grande'), ('', 'Normal'), ('btn-sm', 'Pequeno')], default='', max_length=8, verbose_name='Tamanho')),
                ('left_icon', models.CharField(choices=[('fas fa-download', 'Download'), ('fas fa-file-pdf', 'Arquivo PDF'), ('far fa-file', 'Arquivo Comum')], default='', max_length=32, verbose_name='Ícone Esquerdo')),
                ('right_icon', models.CharField(choices=[('fas fa-download', 'Download'), ('fas fa-file-pdf', 'Arquivo PDF'), ('far fa-file', 'Arquivo Comum')], default='', max_length=32, verbose_name='Ícone Direito')),
            ],
            options={
                'verbose_name': 'Botão',
                'verbose_name_plural': 'Botões',
            },
        ),
    ]
