# Generated by Django 2.1.4 on 2018-12-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_block_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='jumbotron_image',
            field=models.ImageField(default=None, upload_to='img', verbose_name='Jumbotron'),
        ),
    ]
