# Generated by Django 2.1.4 on 2018-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_info_jumbotron_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='jumbotron_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img', verbose_name='Jumbotron'),
        ),
    ]
